# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.CharField(max_length=100)),
                ('master_pw', models.CharField(max_length=1000)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=100)),
                ('site_id', models.CharField(max_length=100)),
                ('site_pw', models.CharField(max_length=500)),
                ('comment', models.TextField(max_length=5000)),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.Account')),
            ],
        ),
    ]
