# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_auto_20160717_0555'),
    ]

    operations = [
    ]
