# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_auto_20160717_0556'),
    ]

    operations = [
    ]
