# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0009_auto_20160717_0606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
